name: bhangari
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5

  firebase_core: ^2.30.0
  firebase_database: ^10.4.0
  firebase_messaging: ^14.8.2
  cloud_firestore: ^4.17.0

  app_usage: ^3.0.1
  usage_stats: ^1.2.0
  device_apps: ^2.2.0
  intl: ^0.19.0
  geolocator: ^12.0.0
  baseflow_plugin_template: ^2.1.2
  flutter_background_service: ^5.0.6
  sqflite: ^2.3.3+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

